version: '3'

services:
  pqai_reranker:
    image: pqai_reranker
    container_name: pqai_reranker
    build: .
    restart: always
    volumes:
      - type: bind
        source: ./assets
        target: /app/assets
    ports:
      - ${PORT}:80
    environment:
      - PORT=${PORT}
      - ENCODER_SRV_ENDPOINT=${ENCODER_SRV_ENDPOINT}
