version: '3.2'

services:
  pqai_reranker_api:
    container_name: pqai_reranker
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80"
    restart: always
    ports: 
      - ${PORT}:80
    volumes:
      - type: bind
        source: ./assets
        target: /app/assets
    environment:
      - PORT=${PORT}
      - ENCODER_SRV_ENDPOINT=${ENCODER_SRV_ENDPOINT}
